- hosts: dvidsbase
  become_user:
  become_method: sudo
  become: yes

  vars_files:
    - private/passwords.yml
  vars:
    output_path: "/tmp/stig-{{ansible_hostname}}.txt"
    update_int: '\d+'
    security_int: ';\d+'
    ansible_become_pass: "{{ ansible_become_pass }}"

  pre_tasks:

    - name: install required packages
      become: true
      package:
        name:
          - ntp
          - ntpdate
          - aide
          - auditd
          - audispd-plugins
        state: present
        update_cache: yes
        cache_valid_time: 3600
        dpkg_options: 'force-confnew'

  tasks:

    - name: check for graphical interface
      stat:
        path: /etc/X11/default-display-manager
      register: dm_file

    - name: check to see if we are booting with EFI or UEFI
      set_fact:
        booted_with_efi: "{{ ansible_mounts | selectattr('mount', 'equalto', '/boot/efi') | list | length > 0 }}"
        has_display: "{{ dm_file.stat.exists }}"

   
    # - include_tasks: tasks/stig/ubuntu/18.04/V-219185.yml  # disable this STIG when run on AWS
    # - include_tasks: tasks/stig/ubuntu/18.04/V-219191.yml  # default /var/log 775, don't apply this STIG to EBS volume in EC2

    - include_tasks: tasks/stig/ubuntu/18.04/V-219316.yml  # PAM pkcs11 pam_pkcs11.conf
    - include_tasks: tasks/stig/ubuntu/18.04/V-219317.yml  # PAM pkcs11 smartcard auth
    - include_tasks: tasks/stig/ubuntu/18.04/V-219166.yml  # PAM pam_tally.so
    - include_tasks: tasks/stig/ubuntu/18.04/V-219164.yml  # PAM pam_faildelay.so

    - include_tasks: tasks/stig/ubuntu/18.04/V-219227.yml    
    - include_tasks: tasks/stig/ubuntu/18.04/V-219241.yml   
    - include_tasks: tasks/stig/ubuntu/18.04/V-219244.yml
    - include_tasks: tasks/stig/ubuntu/18.04/V-219246.yml
    - include_tasks: tasks/stig/ubuntu/18.04/V-219247.yml
    - include_tasks: tasks/stig/ubuntu/18.04/V-219255.yml
    - include_tasks: tasks/stig/ubuntu/18.04/V-219256.yml
    - include_tasks: tasks/stig/ubuntu/18.04/V-219262.yml
    - include_tasks: tasks/stig/ubuntu/18.04/V-219263.yml
    - include_tasks: tasks/stig/ubuntu/18.04/V-219264.yml
    - include_tasks: tasks/stig/ubuntu/18.04/V-219265.yml
    - include_tasks: tasks/stig/ubuntu/18.04/V-219266.yml
    - include_tasks: tasks/stig/ubuntu/18.04/V-219283.yml
    - include_tasks: tasks/stig/ubuntu/18.04/V-219288.yml
    - include_tasks: tasks/stig/ubuntu/18.04/V-219290.yml
    - include_tasks: tasks/stig/ubuntu/18.04/V-219294.yml

    - include_tasks: tasks/stig/ubuntu/18.04/V-219254.yml
    - include_tasks: tasks/stig/ubuntu/18.04/V-219253.yml
    - include_tasks: tasks/stig/ubuntu/18.04/V-219198.yml
    - include_tasks: tasks/stig/ubuntu/18.04/V-219180.yml
    - include_tasks: tasks/stig/ubuntu/18.04/V-219167.yml
    - include_tasks: tasks/stig/ubuntu/18.04/V-219170.yml
    - include_tasks: tasks/stig/ubuntu/18.04/v219234.yml
    - include_tasks: tasks/stig/ubuntu/18.04/v219328.yml
    - include_tasks: tasks/stig/ubuntu/18.04/v219232.yml
    - include_tasks: tasks/stig/ubuntu/18.04/v219233.yml
    - include_tasks: tasks/stig/ubuntu/18.04/V-219267.yml
    - include_tasks: tasks/stig/ubuntu/18.04/V-219242.yml
    - include_tasks: tasks/stig/ubuntu/18.04/v219337.yml
    - include_tasks: tasks/stig/ubuntu/18.04/v219236.yml
    - include_tasks: tasks/stig/ubuntu/18.04/v219182.yml
    - include_tasks: tasks/stig/ubuntu/18.04/v219196.yml
    - include_tasks: tasks/stig/ubuntu/18.04/v219195.yml
    - include_tasks: tasks/stig/ubuntu/18.04/v219342.yml
    - include_tasks: tasks/stig/ubuntu/18.04/v219340.yml
    - include_tasks: tasks/stig/ubuntu/18.04/V-219296.yml
    - include_tasks: tasks/stig/ubuntu/18.04/v219341.yml
    - include_tasks: tasks/stig/ubuntu/18.04/v219186.yml
    - include_tasks: tasks/stig/ubuntu/18.04/v219291.yml
    - include_tasks: tasks/stig/ubuntu/18.04/v219292.yml
    - include_tasks: tasks/stig/ubuntu/18.04/V-219289.yml
    - include_tasks: tasks/stig/ubuntu/18.04/v219197.yml
    - include_tasks: tasks/stig/ubuntu/18.04/v219221.yml
    - include_tasks: tasks/stig/ubuntu/18.04/v219217.yml
    - include_tasks: tasks/stig/ubuntu/18.04/v219219.yml
    - include_tasks: tasks/stig/ubuntu/18.04/v219220.yml
    - include_tasks: tasks/stig/ubuntu/18.04/V-219297.yml
    - include_tasks: tasks/stig/ubuntu/18.04/v219274.yml
    - include_tasks: tasks/stig/ubuntu/18.04/v219273.yml
    - include_tasks: tasks/stig/ubuntu/18.04/v219295.yml
    - include_tasks: tasks/stig/ubuntu/18.04/v219277.yml
    - include_tasks: tasks/stig/ubuntu/18.04/v219275.yml
    - include_tasks: tasks/stig/ubuntu/18.04/v219278.yml
    - include_tasks: tasks/stig/ubuntu/18.04/v219298.yml
    - include_tasks: tasks/stig/ubuntu/18.04/v219226.yml
    - include_tasks: tasks/stig/ubuntu/18.04/v219223.yml
    - include_tasks: tasks/stig/ubuntu/18.04/v219158.yml
    - include_tasks: tasks/stig/ubuntu/18.04/v219157.yml
    - include_tasks: tasks/stig/ubuntu/18.04/V-219268.yml
    - include_tasks: tasks/stig/ubuntu/18.04/V-219269.yml
    - include_tasks: tasks/stig/ubuntu/18.04/V-219272.yml
    - include_tasks: tasks/stig/ubuntu/18.04/v219211.yml
    - include_tasks: tasks/stig/ubuntu/18.04/v219177.yml
    - include_tasks: tasks/stig/ubuntu/18.04/v219212.yml
    - include_tasks: tasks/stig/ubuntu/18.04/v219312.yml
    - include_tasks: tasks/stig/ubuntu/18.04/v219314.yml
    - include_tasks: tasks/stig/ubuntu/18.04/v219224.yml
    - include_tasks: tasks/stig/ubuntu/18.04/v219336.yml
    - include_tasks: tasks/stig/ubuntu/18.04/v219209.yml
    - include_tasks: tasks/stig/ubuntu/18.04/v219335.yml
    - include_tasks: tasks/stig/ubuntu/18.04/v219313.yml
    - include_tasks: tasks/stig/ubuntu/18.04/v219314.yml
    - include_tasks: tasks/stig/ubuntu/18.04/v219224.yml
    - include_tasks: tasks/stig/ubuntu/18.04/v219336.yml
    - include_tasks: tasks/stig/ubuntu/18.04/v219330.yml
    - include_tasks: tasks/stig/ubuntu/18.04/v219335.yml
    - include_tasks: tasks/stig/ubuntu/18.04/v219208.yml
    - include_tasks: tasks/stig/ubuntu/18.04/v219313.yml
    - include_tasks: tasks/stig/ubuntu/18.04/v219207.yml
    - include_tasks: tasks/stig/ubuntu/18.04/v219243.yml
    - include_tasks: tasks/stig/ubuntu/18.04/V-219245.yml
    - include_tasks: tasks/stig/ubuntu/18.04/v219213.yml
    - include_tasks: tasks/stig/ubuntu/18.04/V-219214.yml
    - include_tasks: tasks/stig/ubuntu/18.04/V-219215.yml
    - include_tasks: tasks/stig/ubuntu/18.04/V-219216.yml
    - include_tasks: tasks/stig/ubuntu/18.04/V-219284.yml
    - include_tasks: tasks/stig/ubuntu/18.04/v219285.yml
    - include_tasks: tasks/stig/ubuntu/18.04/v219286.yml
    - include_tasks: tasks/stig/ubuntu/18.04/v219287.yml
    - include_tasks: tasks/stig/ubuntu/18.04/v219303.yml
    - include_tasks: tasks/stig/ubuntu/18.04/v219300.yml
    - include_tasks: tasks/stig/ubuntu/18.04/v219299.yml
    - include_tasks: tasks/stig/ubuntu/18.04/v219302.yml
    - include_tasks: tasks/stig/ubuntu/18.04/v219309.yml
    - include_tasks: tasks/stig/ubuntu/18.04/v219310.yml
    - include_tasks: tasks/stig/ubuntu/18.04/v219311.yml
    - include_tasks: tasks/stig/ubuntu/18.04/v219238.yml
    - include_tasks: tasks/stig/ubuntu/18.04/v219176.yml
    - include_tasks: tasks/stig/ubuntu/18.04/v219239.yml
    - include_tasks: tasks/stig/ubuntu/18.04/v219199.yml
    - include_tasks: tasks/stig/ubuntu/18.04/v219200.yml
    - include_tasks: tasks/stig/ubuntu/18.04/v219218.yml
    - include_tasks: tasks/stig/ubuntu/18.04/v219338.yml
    - include_tasks: tasks/stig/ubuntu/18.04/V-219231.yml
    - include_tasks: tasks/stig/ubuntu/18.04/V-219168.yml
    - include_tasks: tasks/stig/ubuntu/18.04/V-219270.yml
    - include_tasks: tasks/stig/ubuntu/18.04/V-219271.yml
    - include_tasks: tasks/stig/ubuntu/18.04/v219279.yml
    - include_tasks: tasks/stig/ubuntu/18.04/v219280.yml
    - include_tasks: tasks/stig/ubuntu/18.04/v219282.yml
    - include_tasks: tasks/stig/ubuntu/18.04/v219201.yml
    - include_tasks: tasks/stig/ubuntu/18.04/V-219306.yml
    - include_tasks: tasks/stig/ubuntu/18.04/v219202.yml
    - include_tasks: tasks/stig/ubuntu/18.04/v219203.yml
    - include_tasks: tasks/stig/ubuntu/18.04/v219155.yml
    - include_tasks: tasks/stig/ubuntu/18.04/v219206.yml
    - include_tasks: tasks/stig/ubuntu/18.04/v219156.yml
    - include_tasks: tasks/stig/ubuntu/18.04/V-219261.yml
    - include_tasks: tasks/stig/ubuntu/18.04/V-219252.yml
    - include_tasks: tasks/stig/ubuntu/18.04/V-219229.yml
    - include_tasks: tasks/stig/ubuntu/18.04/V-219230.yml
    - include_tasks: tasks/stig/ubuntu/18.04/V-219228.yml
    - include_tasks: tasks/stig/ubuntu/18.04/V-219323.yml
    - include_tasks: tasks/stig/ubuntu/18.04/V-219248.yml
    - include_tasks: tasks/stig/ubuntu/18.04/V-219249.yml
    - include_tasks: tasks/stig/ubuntu/18.04/V-219250.yml
    - include_tasks: tasks/stig/ubuntu/18.04/V-219320.yml
    - include_tasks: tasks/stig/ubuntu/18.04/V-219251.yml
    - include_tasks: tasks/stig/ubuntu/18.04/V-219319.yml
    - include_tasks: tasks/stig/ubuntu/18.04/V-219240.yml
    - include_tasks: tasks/stig/ubuntu/18.04/V-219293.yml
    - include_tasks: tasks/stig/ubuntu/18.04/V-219346.yml
    - include_tasks: tasks/stig/ubuntu/18.04/V-219188.yml
    - include_tasks: tasks/stig/ubuntu/18.04/V-219187.yml
    - include_tasks: tasks/stig/ubuntu/18.04/V-219190.yml
    - include_tasks: tasks/stig/ubuntu/18.04/V-219149.yml
    - include_tasks: tasks/stig/ubuntu/18.04/V-219339.yml
    - include_tasks: tasks/stig/ubuntu/18.04/V-219161.yml
    - include_tasks: tasks/stig/ubuntu/18.04/V-219276.yml
    - include_tasks: tasks/stig/ubuntu/18.04/V-219327.yml
    - include_tasks: tasks/stig/ubuntu/18.04/V-219178.yml
    - include_tasks: tasks/stig/ubuntu/18.04/V-219179.yml
    - include_tasks: tasks/stig/ubuntu/18.04/V-219163.yml
    - include_tasks: tasks/stig/ubuntu/18.04/V-219174.yml
    - include_tasks: tasks/stig/ubuntu/18.04/V-219175.yml
    - include_tasks: tasks/stig/ubuntu/18.04/V-219172.yml
    - include_tasks: tasks/stig/ubuntu/18.04/V-219173.yml
    - include_tasks: tasks/stig/ubuntu/18.04/V-219332.yml
    - include_tasks: tasks/stig/ubuntu/18.04/V-219210.yml
    - include_tasks: tasks/stig/ubuntu/18.04/V-219162.yml
    - include_tasks: tasks/stig/ubuntu/18.04/V-219165.yml
    - include_tasks: tasks/stig/ubuntu/18.04/V-219165.yml
    - include_tasks: tasks/stig/ubuntu/18.04/V-219301.yml
    - include_tasks: tasks/stig/ubuntu/18.04/V-219237.yml
    - include_tasks: tasks/stig/ubuntu/18.04/V-219153.yml
    - include_tasks: tasks/stig/ubuntu/18.04/V-219322.yml
    - include_tasks: tasks/stig/ubuntu/18.04/V-219152.yml
    - include_tasks: tasks/stig/ubuntu/18.04/V-219204.yml
    - include_tasks: tasks/stig/ubuntu/18.04/V-219205.yml
    - include_tasks: tasks/stig/ubuntu/18.04/V-219181.yml
    - include_tasks: tasks/stig/ubuntu/18.04/V-219325.yml
    - include_tasks: tasks/stig/ubuntu/18.04/V-219307.yml
    - include_tasks: tasks/stig/ubuntu/18.04/V-219304.yml
    - include_tasks: tasks/stig/ubuntu/18.04/V-219318.yml
    - include_tasks: tasks/stig/ubuntu/18.04/V-219315.yml
    - include_tasks: tasks/stig/ubuntu/18.04/V-219257.yml
    - include_tasks: tasks/stig/ubuntu/18.04/V-219343.yml
    - include_tasks: tasks/stig/ubuntu/18.04/V-219344.yml
    - include_tasks: tasks/stig/ubuntu/18.04/V-219193.yml
    - include_tasks: tasks/stig/ubuntu/18.04/V-219192.yml
    - include_tasks: tasks/stig/ubuntu/18.04/V-219326.yml
    - include_tasks: tasks/stig/ubuntu/18.04/V-219194.yml
    - include_tasks: tasks/stig/ubuntu/18.04/V-219184.yml
    - include_tasks: tasks/stig/ubuntu/18.04/V-219235.yml
    - include_tasks: tasks/stig/ubuntu/18.04/V-219212.yml
    - include_tasks: tasks/stig/ubuntu/18.04/V-219211.yml
    - include_tasks: tasks/stig/ubuntu/18.04/V-219177.yml
    - include_tasks: tasks/stig/ubuntu/18.04/V-219281.yml


    # - include: "{{ item }}"
    #   with_fileglob:
    # # #     - /home/thuan/projects/sec/fix_snmp.yml
    # #     #  - /home/thuan/projects/sec/upgrade_kernel.yml
    #     - /home/thuan/projects/sec/dropbear.yml
        # - /home/thuan/projects/sec/manage_engine_agent_installation.yml
