---

- name: ensure Ubuntu 18 is able to generate audit records successful for crontab.
  hosts: localhost
  become: true

  vars:
    stig_id: V-219276
    stig_text: "FAILED. Ubuntu does not generate audit record when attempts to use crontab command."
    target_file: /etc/audit/rules.d/stig.rules


  tasks:
     
    - name: check for the file
      stat:
        path: "{{ target_file }}"
      register: rules_file

    - set_fact:
        stig_text: "FAILED. {{ target_file }} file does not exist."
      when: rules_file.stat.exists == False
 
    - name: check for audit rules
      shell: auditctl -l | grep -w crontab
      register: audit_check
      failed_when: audit_check.stdout | length > 0

    - assert:
        that: 
        - audit_check != "crontab"
        - audit_check != ('-a always,exit -F path=/usr/bin/crontab -F perm=x -F auid>=1000 -F auid!=-1 -k privileged-crontab')
         
    - set_fact:
        stig_text: "PASSED"
  
    - name: configure the audit system to generate an audit event for any successful/unsuccessful use of the "crontab" command.
      lineinfile:
        path: "/etc/audit/rules.d/stig.rules"
        create: yes
        owner: root
        group: root
        state: present
        line: |
          -a always,exit -F path=/usr/bin/crontab -F perm=x -F auid>=1000 -F auid!=4294967295 -k privileged-crontab
      register: file_updated

    - name: reload the rules file
      shell: augenrules --load
      register: reload_rules

    - set_fact:
        stig_text: "PASSED"
      when: file_updated.failed == false

    - debug:
        msg: "{{ stig_id }} {{stig_text}}"

#  always:

#    - local_action: lineinfile line="{{ stig_id }} {{ stig_text }}" path="{{ output_path }}" create=yes
