---

- name: ensure Ubuntu 18 uncomplicated firewall service is enabled and running.
  hosts: localhost
  become: true
 
  vars:
    stig_id: V-219337
    stig_text: "The Ubuntu operating system must enable and run the uncomplicated firewall(ufw)."


  tasks:
    - block:

        - name: check if firewall is enabled.          
          shell: 'systemctl is-enabled ufw'
          register: ufw_enable
          failed_when: ufw_enable.stdout == 'disabled'


        - name: check if firewall is running           
          shell: 'systemctl is-active ufw'
          register: ufw_active
          failed_when: ufw_active.stdout == 'inactive'

        - set_fact:
            stig_text: "{{ stig_id }} PASSED"


      rescue:

        - name: change the firewall status to 'enabled' if it's disabled.        
          shell: systemctl enable ufw.service
          register: ufw_enabled_service
     
        - name: set firewall service to 'running' if it not running.                 
          shell: systemctl start ufw.service
          register: ufw_active_running

        - set_fact:
            stig_text: "{{ stig_id }} PASSED"
          when: 
            - ufw_enabled_service.rc == 0
            - ufw_active_running.rc == 0

        - debug:
            msg: "{{ stig_text }}"