---

- name: ensure Ubuntu 18 must deploy Endpoint Security for Linux Threat Prevention (ENSLTP).
  hosts: localhost
  become: true

  vars:
    stig_id: V-219159
    stig_text: "FAILED. Isectp package is not installed "
    

#  local_action: lineinfile regexp='^V-219159' path="{{ output_path }}" state=absent

  tasks:
    - block: 
        - name: check for isectp installation package
          shell: dpkg -l | grep isectp
          register: audit_check
          failed_when: audit_check.rc == 1
          
        - fail:
            msg: "FAILED. isectp package does not exist."
          when: audit_check.rc == 1

        - set_fact:
            stig_text: "PASSED"

      rescue:
        - name: Install isectp package 
          apt:
            name: isectp
            state: present
          register: install_isectp


        - name: check for isectp daemon is running
          shell: ps -ef | grep isectpd
          register: daemon_check
          failed_when: daemon_check.rc != 0
   
        - set_fact:
            stig_text: "PASSED"
          when: 
            - install_isectp.failed == false
            - daemon_check.rc == 0

      
        - debug:
            msg: "{{ stig_id }} {{stig_text}}"

#      always:
#        - local_action: lineinfile line="{{ stig_id }} {{ stig_text }}" path="{{ output_path }}" create=yes
