---

- name: verify that the logs ownership/perms are belong to system administrators and service accounts.
  hosts: localhost
  vars:
    stig_id: Test-12345
    stig_text: 'FAILED. The Apache web server log files must only be accessible by privileged users.'
    target_file: /tmp/

    output_path: "/tmp/stig-{{ansible_hostname}}.txt"
    local_action: lineinfile regexp='^Test-12345' path="{{ output_path }}" state=absent

  tasks:
    - name:
      block:
        - name: verify the files' permissions and ownership
          find:
            paths: "{{ target_file }}"
            patterns: "*.txt"
          register: permissions
          failed_when: >
            (permissions.files | selectattr('pw_name', '!=', 'root') | list) or
            (permissions.files | selectattr('gr_name', '!=', 'adm') | list) or
            (permissions.files | selectattr('mode', '!=', '0640') | list)

        - set_fact:
            stig_text: "{{ stig_id }} PASSED"

      rescue:
        - name: change the permission and ownership of the files
          become: true
          file:
            path: "{{ item.path }}"
            owner: root
            group: adm
            mode: 0640
          loop: "{{ permissions.files }}"
          loop_control:
            label: "{{ item.path }}"
          register: change_perms

        - set_fact:
            stig_text: "PASSED"
          when: change_perms.changed | bool

        - debug:
            msg: "{{ stig_id }} {{ stig_text }}"

      always:
        - local_action: lineinfile line="{{ stig_id }} {{ stig_text }}" path="{{ output_path }}" create=yes