---

- name: verify that the logs ownership/perms are belong to system administrators and service accounts.
  hosts: localhost
  vars:
    stig_id: Test-12345
    stig_text: 'FAILED. The Apache web server log files must only be accessible by privileged users.'
    target_file: /tmp/

    output_path: "/tmp/stig-{{ansible_hostname}}.txt"
    local_action: lineinfile regexp='^Test-12345' path="{{ output_path }}" state=absent

  tasks:
    - name:
      block:
        - name: find files
          find:
            paths: "{{ target_file }}"
            patterns: "*.txt"
          register: file

        - name: change the permission and ownership of the files
          become: true
          file:
            path: "{{ item.path }}"
            owner: root
            group: adm
            mode: 0640
          loop: "{{ file.files }}"
          loop_control:
            label: "{{ item.path }}"
          register: change_perms

        - name: List of security remediation run during this audit
          debug:
            var: change_perms.results | selectattr('changed') | map(attribute='diff') | list

        - set_fact:
            stig_text: "PASSED"

        - debug:
            msg: "{{ stig_id }} {{ stig_text }}"      
                       
      rescue:
        - set_fact:
            stig_text: FAILED    

        - debug:
            msg: "{{ stig_id }} {{ stig_text }}"      

      always:
        - local_action: lineinfile line="{{ stig_id }} {{ stig_text }}" path="{{ output_path }}" create=yes